title: Hijack Security Blog
description: >-
  A technology blog focused on Security, DevSecOps, AI, and Development.
  Exploring the intersection of technology and cybersecurity.
baseurl: ""
url: "https://blog.hijacksecurity.org"

twitter_username: hijacksecurity
github_username:  hijacksecurity

markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

sass:
  style: expanded
  sourcemap: never

permalink: /:year/:month/:day/:title/

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hijack Security"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

show_excerpts: true

header_pages:
  - _pages/posts.html
  - _pages/tags.html
  - about.md